---
title: "Summary statistics for GIMA measures"
author:
- Kai Xia
date: "`r format(Sys.time(), '%d %B %Y')`"

output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Descriptive Statistics of measures

```{r echo=FALSE,results='asis',include=TRUE, cache=FALSE,message=FALSE}
library(xlsx)
library(knitr)
library(moments)

#dataset = 'neo'
#dir_out = 'output'

if(Sys.info()["sysname"] == 'Windows'){
  dir1 = 'C:/Users/kxia/OneDrive - University of North Carolina at Chapel Hill/github/gmia/scripts'
} else{
  dir1 = '/Users/kaixia/OneDrive - University of North Carolina at Chapel Hill/github/gmia/scripts'
}

setwd(dir1)

dir_mb = '../processed_data'
dir_raw = '../raw_data'
dir_cvrt = sprintf('%s/cvrt', dir_raw)
dir_brain = sprintf('%s/braindata', dir_raw)
dir_out = '../results'
dir_beha = sprintf('%s/behaviordata', dir_raw)


#dir1 = 'Z:/Kai/bios_brain/microbiome/GIMA'


N <- function(x) {
    length(which(!is.na(x)))
}

#pdf('boxplot_measures.pdf',paper='special',width=7,height=7)
## load the age
#dat1 = read.xlsx(sprintf('%s/GMIAMaskBehavior_7AUG17.xlsx',dir_beha),sheetName = 'MaskScoresDescriptiveStats',header=TRUE)

dat1 = read.csv(sprintf('%s/GMIAmask_6JUN18.csv',dir_beha), header=TRUE)
#dat1 = read.delim(sprintf('%s/MELT_data_age_0802.txt',dir1),strings=TRUE,header=TRUE)


colNames = colnames(dat1)[-1]
#mx1 = summary(dat1[,-1])

sumNames = c('N','min','max','mean','median','sd','skewness','kurtosis')
digit =    c(0,   2,    2,     2,     2,      2,    2,         2)
mx1 = matrix(NA,length(colNames),length(sumNames))

for(i in 1:length(sumNames)){
  
  vals = apply(dat1[,-1],2,sumNames[i])
  mx1[,i] = vals
}

rownames(mx1) = colNames
colnames(mx1) = sumNames

kable(mx1,caption = 'Summary statistics of GIMA',digits = digit)

```



## Correlation Among Measures
In EXCEL file correlation_GIMA.xlsx

```{r echo=FALSE,results='asis',include=TRUE, cache=FALSE,message=FALSE, fig.width=7, fig.height=7,fig.show='asis',out.width='150%',fig.align='left'}
mx2 = cor(dat1[,-1])
fileout_corr = sprintf('%s/correlation_GIMA.xlsx',dir_out)
write.xlsx(mx2, file=fileout_corr, sheetName = 'PCC')

### calculate corr test p-value for the matrix
dat1_sub = dat1[,-1]
N = dim(dat1_sub)[2]
mx_pval = matrix(NA,N,N)

for(j in 1:N) {
  for(k in 1:N) {
    pval = cor.test(dat1_sub[,j],dat1_sub[,k])$p.value
    mx_pval[j,k] = pval
  }
}
colnames(mx_pval) = colnames(dat1_sub)
rownames(mx_pval) = colnames(dat1_sub)

fileout_corr_test = sprintf('%s/correlation_test_pval_GIMA.xlsx',dir_out)
write.xlsx(mx_pval, file=fileout_corr_test, sheetName = 'PCC pval')






## heatmap
# Get lower triangle of the correlation matrix
  get_lower_tri<-function(cormat){
    cormat[upper.tri(cormat)] <- NA
    return(cormat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  
par(mar = c(0, 0, 0, 0))
upper_tri <- get_upper_tri(mx2)
library(reshape2)
melted_cormat <- melt(upper_tri, na.rm = TRUE)
# Heatmap
library(ggplot2)
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 90, vjust = 1, 
    size = 10, hjust = 1)
    ,axis.title.x = element_blank(),
    axis.title.y = element_blank()
    )+
 coord_fixed()



```




## Histograms of measures
```{r,echo=FALSE, fig.width=3, fig.height=3,fig.show='asis',out.width='35%'}
#```{r, echo=FALSE, fig.width=6.5,fig.height=10}
#```{r echo=FALSE,results='asis',include=TRUE, cache=FALSE,message=FALSE}
#cat('\n') 
#layout(matrix(1:6,3,2,byrow=TRUE))
for(i in 1:length(colNames)){
  # i =1;
 hist(dat1[,colNames[i]],xlab=colNames[i],breaks=10,main='') 
}


```




```{r loading, eval=FALSE}
### weighted unifrac
if(Sys.info()["sysname"] == 'Windows'){
  dir1 = 'C:/Users/kxia/OneDrive - University of North Carolina at Chapel Hill/github/gmia/scripts'
} else{
  dir1 = '/Users/kaixia/OneDrive - University of North Carolina at Chapel Hill/github/gmia/scripts'
}

setwd(dir1)

dir_mb = '../processed_data'
dir_raw = '../raw_data'
dir_cvrt = sprintf('%s/cvrt', dir_raw)
dir_brain = sprintf('%s/braindata', dir_raw)
dir_out = '../results'
dir_beha = sprintf('%s/behaviordata', dir_raw)

datasets = c('neo','yr1')

for(dataset in datasets){
  dir_beta = sprintf('%s/diversity/%s/core_div/bdiv_even5000', dir_raw, dataset)
  
  file_pc = sprintf('%s/weighted_unifrac_pc_mod.txt',dir_beta)
  mx_pc = read.delim(file_pc,header=FALSE,strings=FALSE)
  
  pdf(sprintf('%s/PCA_loading_%s.pdf', dir_out, dataset),width=4*3,height=4*5,paper='special')
  layout(matrix(1:2,1,2,byrow=TRUE))
  mch1 = match(colnames(data_matrix), mx_pc[,1])
  #pc1 = mx_pc[mch1,2]
  #pc2 = mx_pc[mch1,3]
  pcs = mx_pc[mch1,2:3]
  cor_mx=cor(pcs,t(data_matrix))
  
  for(i in 1:dim(pcs)[2]){
    barplot(cor_mx[i,],main=paste('PC',i,'loading'),horiz=TRUE,names.arg=genusNames,las=2,cex.names = 0.7,xlab='Corerlation Coefficient')
  }  
  dev.off()
}
```



